#!/usr/bin/env Rscript
# Generate a representative clinical TFL RTF using r2rtf.
# Output: prototype/rtf-reader-proto/test-data/reference-tfl-100p.rtf

library(r2rtf)

out_dir <- "test-data"
out_file <- file.path(out_dir, "reference-tfl-100p.rtf")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

# Each table will have this many rows.
rows_per_table <- 180
num_tables <- 6

set.seed(42)

make_table <- function(table_id) {
  n <- rows_per_table
  data.frame(
    USUBJID = sprintf("01-703-%04d", sample(1000:9999, n, replace = TRUE)),
    AGE = sample(18:85, n, replace = TRUE),
    SEX = sample(c("M", "F"), n, replace = TRUE, prob = c(0.5, 0.5)),
    RACE = sample(
      c("WHITE", "ASIAN", "BLACK OR AFRICAN AMERICAN", "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER"),
      n,
      replace = TRUE,
      prob = c(0.6, 0.25, 0.1, 0.05)
    ),
    ARM = sample(c("Placebo", "Drug 10 mg", "Drug 20 mg"), n, replace = TRUE),
    不良反应术语 = sample(
      c("头痛", "恶心", "腹泻", "疲劳", "皮疹", "头晕", "呕吐", "失眠"),
      n,
      replace = TRUE
    ),
    stringsAsFactors = FALSE
  )
}

# Build RTF body by concatenating encoded tables.
rtf_parts <- list()

for (i in seq_len(num_tables)) {
  df <- make_table(i)

  rtf <- df |>
    rtf_page(
      orientation = "landscape",
      margin = c(1.0, 1.0, 1.0, 1.0, 0.5, 0.5)
    ) |>
    rtf_title(
      paste0("Table ", i, ": Demographic and Baseline Characteristics"),
      paste0("Safety Population; Table generated by r2rtf for RTF Reader Prototype")
    ) |>
    rtf_colheader(
      paste(
        "Subject ID | Age (years) | Sex | Race | Treatment Arm | 不良反应术语 / Adverse Event Term",
        collapse = ""
      )
    ) |>
    rtf_body(
      text_font = 1,
      text_justification = "c"
    ) |>
    rtf_footnote("注：此表为合成数据，仅用于 RTF 阅读器原型性能测试。Source: r2rtf.")

  rtf_parts[[i]] <- rtf_encode(rtf)
}

# Combine parts and write.
full_rtf <- paste(unlist(rtf_parts), collapse = "")
write_rtf(full_rtf, out_file)

message("Generated: ", out_file)
message("Approximate size: ", round(file.size(out_file) / 1024, 1), " KB")
