#!/usr/bin/env python3
"""
Generate synthetic clinical TFL RTF files with embedded EMF images.
Uses EMF files generated by R (tools/generate-emf-figures.R).
"""

import argparse
import os
import random
import glob


def make_font_table():
    return (
        "{\\fonttbl"
        "{\\f0\\froman\\fcharset0 Times New Roman;}"
        "{\\f1\\fswiss\\fcharset0 Arial;}"
        "{\\f2\\fnil\\fcharset134 \\u24494?\\u-27253?\\u-30335?;}"
        "}"
    )


def make_color_table():
    return "{\\colortbl ;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}"


def make_header():
    return (
        "{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1033\\deflangfe2052"
        + make_font_table()
        + make_color_table()
        + "{\\*\\generator RTF Reader Prototype Synthetic Generator with Images;}"
        "\\paperw15840\\paperh12240\\margl1440\\margr1440\\margt1440\\margb1440"
        "\\landscape"
    )


def emf_to_rtf_pict(emf_path: str, idx: int) -> bytes:
    """Embed an EMF file as an RTF \pict destination using \bin."""
    with open(emf_path, "rb") as f:
        data = f.read()

    # 6 inch x 4 inch display size in twips
    picwgoal = 8640
    pichgoal = 5760
    # HIMETRIC: 6 inch = 152.4 mm = 15240, 4 inch = 101.6 mm = 10160
    picw = 15240
    pich = 10160

    prefix = (
        "{\\pict\\emfblip"
        f"\\picw{picw}\\pich{pich}"
        f"\\picwgoal{picwgoal}\\pichgoal{pichgoal}"
        f"\\bin{len(data)} "
    ).encode("latin-1")
    suffix = b"}"
    return prefix + data + suffix


def make_table_row_header(widths):
    parts = ["\\trowd\\trgaph108\\trleft0\\trqc"]
    for w in widths:
        parts.append(
            f"\\clbrdrt\\brdrs\\brdrw15\\clbrdrl\\brdrs\\brdrw15\\clbrdrb\\brdrs\\brdrw15\\clbrdrr\\brdrs\\brdrw15\\clvertalt\\cellx{w}"
        )
    return "".join(parts)


def make_row(cells, widths):
    parts = [make_table_row_header(widths)]
    for c, w in zip(cells, widths):
        parts.append(
            f"\\pard\\hyphpar0\\sb15\\sa15\\fi0\\li0\\ri0\\qc\\fs18{{\\f0 {c}}}\\cell"
        )
    parts.append("\\intbl\\row\\pard")
    return "".join(parts)


def make_table(table_id, n_rows, rows_per_page: int = 10):
    widths = [2040, 1500, 1200, 3600, 2000, 2400]
    header = ["Subject ID", "Age", "Sex", "Race", "Arm", "不良事件 / AE"]
    rows = [make_row(header, widths)]

    sexes = ["M", "F"]
    races = [
        "WHITE",
        "ASIAN",
        "BLACK OR AFRICAN AMERICAN",
        "NATIVE HAWAIIAN",
    ]
    arms = ["Placebo", "Drug 10 mg", "Drug 20 mg"]
    aes = ["头痛", "恶心", "腹泻", "疲劳", "皮疹", "头晕", "呕吐", "失眠"]

    for i in range(n_rows):
        cells = [
            f"01-703-{random.randint(1000, 9999):04d}",
            str(random.randint(18, 85)),
            random.choice(sexes),
            random.choice(races),
            random.choice(arms),
            random.choice(aes),
        ]
        rows.append(make_row(cells, widths))
        if (i + 1) % rows_per_page == 0:
            rows.append("\\page")

    title = (
        f"\\pard\\qc\\fs24{{\\b Table {table_id}: Demographic and Baseline Characteristics}}\\par"
        f"\\pard\\qc\\fs18 Safety Population — Synthetic data for RTF prototype\\par\\par"
    )
    footnote = (
        "\\pard\\qc\\fs16 注：此表为合成数据，仅用于 RTF 阅读器原型性能测试。\\par"
    )
    return title + "".join(rows) + footnote


def make_figure(fig_idx: int, emf_bytes: bytes, caption: str) -> bytes:
    title = (
        f"\\pard\\qc\\fs24{{\\b Figure {fig_idx}: {caption}}}\\par"
        f"\\pard\\qc\\fs18 Synthetic figure for image prototype\\par\\par"
    ).encode("utf-8")
    body = emf_bytes
    footnote = "\\pard\\qc\\fs16 注：此图为合成数据。\\par".encode("utf-8")
    return title + body + footnote


def generate(target_pages: int, out_dir: str = "test-data"):
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"synthetic-tfl-images-{target_pages}p.rtf")

    fig_dir = os.path.join(out_dir, "figures")
    fig_files = sorted(glob.glob(os.path.join(fig_dir, "figure-*.emf")))
    if not fig_files:
        raise FileNotFoundError(f"No EMF figures found in {fig_dir}. Run generate-emf-figures.R first.")

    # Load all figure bytes
    fig_captions = [
        "Scatter Plot", "Treatment Response", "Age Distribution", "Lab Value Histogram",
        "Kaplan-Meier Curve", "Forest Plot", "Longitudinal Values", "Subject Disposition",
        "Response Density", "Correlation Matrix"
    ]
    fig_bytes_list = [emf_to_rtf_pict(p, i + 1) for i, p in enumerate(fig_files)]

    random.seed(42)

    # Calibration: roughly 10 rows per page, with a figure every 2 pages.
    rows_per_page = 10
    rows_per_table = 120
    figure_every_pages = 2
    figures_count = target_pages // figure_every_pages
    total_rows = target_pages * rows_per_page
    tables = max(1, target_pages // 50)
    rows_per_table_actual = total_rows // tables

    # Build RTF as bytes to safely embed binary picture data
    parts = [make_header().encode("utf-8")]

    figure_idx = 1
    page_counter = 0
    lines_in_page = 0

    for t in range(1, tables + 1):
        parts.append(make_table(t, rows_per_table_actual, rows_per_page).encode("utf-8"))
        lines_in_page += rows_per_table_actual

        # Insert figures inline to reach target density
        while lines_in_page >= figure_every_pages * rows_per_page and figure_idx <= figures_count:
            fig_idx_0 = (figure_idx - 1) % len(fig_bytes_list)
            parts.append(make_figure(figure_idx, fig_bytes_list[fig_idx_0], fig_captions[fig_idx_0]))
            figure_idx += 1
            page_counter += figure_every_pages
            lines_in_page -= figure_every_pages * rows_per_page

        parts.append(b"\\page")

    # Fill remaining figures if any
    while figure_idx <= figures_count:
        fig_idx_0 = (figure_idx - 1) % len(fig_bytes_list)
        parts.append(make_figure(figure_idx, fig_bytes_list[fig_idx_0], fig_captions[fig_idx_0]))
        figure_idx += 1

    parts.append(b"}")

    with open(out_path, "wb") as f:
        for p in parts:
            f.write(p)

    size_mb = os.path.getsize(out_path) / 1024 / 1024
    print(f"Generated: {out_path}")
    print(f"  Target pages: {target_pages}")
    print(f"  Figures:      {figures_count}")
    print(f"  Tables:       {tables}")
    print(f"  File size:    {size_mb:.2f} MB")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--pages", type=int, default=200, help="Target page count")
    parser.add_argument("--out-dir", default="test-data", help="Output directory")
    args = parser.parse_args()
    generate(args.pages, args.out_dir)
